[project]
name = "data-loading"
version = "0.1.0"
description = "Job de chargement de données"
requires-python = ">=3.11"
dependencies = [
    "pyspark==3.5.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
